"""Synthetic demonstration profiles, independent of production image calibration.

Geometry is defined on a 128 x 128 canvas: a 96 x 80 outer rectangle and
64 x 48 inner rectangle; other examples use 4..64 pixel shapes. Binary 255,
8-connectivity, and the Gaussian MAD conversion 1.4826 are algorithm constants.
All masks are disabled. These profiles are examples, not acceptance settings.
"""
from __future__ import annotations

from copy import deepcopy

_PROFILES = {'demo1': {'center_mask_enabled': False,
           'center_mask_use_image_center': True,
           'center_mask_x': 0,
           'center_mask_y': 0,
           'center_mask_width': 0,
           'center_mask_height': 0,
           'edge_mask_enabled': False,
           'edge_inset_all': 0,
           'edge_inset_left': 0,
           'edge_inset_right': 0,
           'edge_inset_top': 0,
           'edge_inset_bottom': 0,
           'background_kernel_size': 15,
           'background_kernel_divisor': 16,
           'background_kernel_min': 3,
           'background_kernel_max': 63,
           'gaussian_sigma': 0.0,
           'mad_scale': 1.4826,
           'noise_sigma_floor': 1e-06,
           'residual_threshold_floor': 4.0,
           'residual_sigma_multiplier': 2.0,
           'candidate_max_value': 255,
           'morph_operation': 'none',
           'morph_kernel': 3,
           'morph_iterations': 1,
           'connectivity': 8,
           'min_component_area_px': 4,
           'min_component_area_ratio': 0.0,
           'max_component_area_px': 4096,
           'max_component_area_ratio': 0.0,
           'component_border_margin_px': 0,
           'background_padding_min_px': 4,
           'background_padding_max_px': 16,
           'background_padding_scale': 1.0,
           'min_background_pixels': 4,
           'cnr_noise_floor': 1e-06},
 'demo2': {'edge_mask_enabled': False,
           'edge_inset_all': 0,
           'edge_inset_left': 0,
           'edge_inset_right': 0,
           'edge_inset_top': 0,
           'edge_inset_bottom': 0,
           'blur_size': 3,
           'adaptive_block_size': 15,
           'adaptive_c': 2.0,
           'max_value': 255,
           'binary_inv': True,
           'morph_operation': 'open',
           'morph_kernel': 3,
           'morph_iterations': 1,
           'contour_mode': 'list',
           'min_area': 16.0,
           'max_area': 4096.0},
 'demo3': {'roi_inset_px': 0,
           'blur_size': 3,
           'morph_operation': 'none',
           'morph_kernel': 3,
           'morph_iterations': 1,
           'adaptive_block_size': 15,
           'adaptive_c': 2.0,
           'binary_inv': True,
           'max_value': 255,
           'contour_mode': 'list',
           'min_area': 16.0,
           'max_area': 4096.0},
 'demo4': {'threshold_method': 'adaptive_mean',
           'max_value': 255,
           'invert': False,
           'blur_size': 3,
           'adaptive_block_size': 15,
           'adaptive_c': 2.0,
           'roi_inset_px': 0,
           'contour_mode': 'list',
           'morph_operation': 'none',
           'morph_kernel': 3,
           'morph_iterations': 1,
           'process_scale': 1.0,
           'min_area': 16.0,
           'max_area': 4096.0,
           'min_circularity': 0.5,
           'min_fill_ratio': 0.0,
           'max_fill_ratio': 0.0},
 'demo5': {'max_value': 255,
           'blur_size': 3,
           'adaptive_block_size': 15,
           'adaptive_c': 2.0,
           'roi_inset_px': 0,
           'contour_mode': 'list',
           'min_area': 16.0,
           'max_area': 4096.0,
           'white_pixel_ratio_threshold': 0.5},
 'demo6': {'edge_mask_enabled': False,
           'edge_inset_all': 0,
           'edge_inset_left': 0,
           'edge_inset_right': 0,
           'edge_inset_top': 0,
           'edge_inset_bottom': 0,
           'adaptive_block_size': 15,
           'adaptive_c': 2.0,
           'max_value': 255,
           'binary_inv': False,
           'contour_mode': 'list',
           'min_area': 16.0,
           'max_area': 4096.0},
 'demo7': {'center_mask_enabled': False,
           'center_mask_use_image_center': True,
           'center_mask_x': 0,
           'center_mask_y': 0,
           'center_mask_width': 0,
           'center_mask_height': 0,
           'edge_mask_enabled': False,
           'edge_inset_all': 0,
           'edge_inset_left': 0,
           'edge_inset_right': 0,
           'edge_inset_top': 0,
           'edge_inset_bottom': 0,
           'threshold_value': 128,
           'max_value': 255,
           'binary_inv': False,
           'contour_mode': 'list',
           'approx_epsilon_ratio': 0.01,
           'min_vertices': 3,
           'min_area': 16.0,
           'max_area': 4096.0},
 'demo8': {'edge_mask_enabled': False,
           'edge_inset_all': 0,
           'edge_inset_left': 0,
           'edge_inset_right': 0,
           'edge_inset_top': 0,
           'edge_inset_bottom': 0,
           'threshold_value': 128,
           'max_value': 255,
           'binary_inv': True,
           'contour_mode': 'list',
           'approx_epsilon_ratio': 0.01,
           'min_vertices': 3,
           'min_area': 16.0,
           'max_area': 4096.0},
 'demo9': {'center_mask_enabled': False,
           'center_mask_use_image_center': True,
           'center_mask_x': 0,
           'center_mask_y': 0,
           'center_mask_width': 0,
           'center_mask_height': 0,
           'edge_mask_enabled': False,
           'edge_inset_all': 0,
           'edge_inset_left': 0,
           'edge_inset_right': 0,
           'edge_inset_top': 0,
           'edge_inset_bottom': 0,
           'threshold_value': 128,
           'max_value': 255,
           'binary_inv': False,
           'contour_mode': 'list',
           'approx_epsilon_ratio': 0.01,
           'min_vertices': 3,
           'min_area': 16.0,
           'max_area': 4096.0},
 'demo10': {'max_value': 255,
            'outer_threshold': 128,
            'outer_invert': False,
            'outer_contour_mode': 'list',
            'outer_target_width': 96,
            'outer_width_tolerance': 3,
            'outer_target_height': 80,
            'outer_height_tolerance': 3,
            'inner_adaptive_block_size': 15,
            'inner_adaptive_c': 2.0,
            'inner_invert': False,
            'inner_contour_mode': 'list',
            'inner_target_width': 64,
            'inner_width_tolerance': 3,
            'inner_target_height': 48,
            'inner_height_tolerance': 3,
            'max_edge_gap': 20,
            'roi_inset_px': 0},
 'demo11': {'mode': 'pass',
            'defect_x': 0,
            'defect_y': 0,
            'defect_width': 16,
            'defect_height': 16},
 'demo12': {'model_id': '',
            'confidence_threshold': 0.5,
            'nms_iou_threshold': 0.5,
            'target_class_ids': '',
            'max_detections': 32,
            'min_box_area_px': 0.0,
            'inference_backend': 'auto',
            'precision': 'fp32',
            'class_agnostic_nms': False},
 'demo13': {'center_mask_enabled': False,
            'center_mask_use_image_center': True,
            'center_mask_x': 0,
            'center_mask_y': 0,
            'center_mask_width': 0,
            'center_mask_height': 0,
            'edge_mask_enabled': False,
            'edge_inset_all': 0,
            'edge_inset_left': 0,
            'edge_inset_right': 0,
            'edge_inset_top': 0,
            'edge_inset_bottom': 0,
            'threshold_value': 128,
            'binary_inv': False,
            'min_area': 16.0,
            'max_area': 4096.0}}


def demo_defaults(detector_id: str) -> dict:
    """Return an independent mutable copy of an explicitly declared demo profile."""
    return deepcopy(_PROFILES[detector_id])
